{
	"version": 1527434420,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/flechaatirante-sheet0.png",
		"images/iflechaatirante-sheet0.png",
		"images/iflechaoriginalatirar-sheet0.png",
		"images/iflechaoriginalatirar-sheet1.png",
		"images/iflechas-sheet0.png",
		"images/iflecha-sheet0.png",
		"images/iboneco-sheet0.png",
		"images/iboneco-sheet1.png",
		"images/iboneco-sheet2.png",
		"images/iarco-sheet0.png",
		"images/imão-sheet0.png",
		"images/imonstroceu-sheet0.png",
		"images/imonstrochão-sheet0.png",
		"images/imonstrochão-sheet1.png",
		"images/isetting-sheet0.png",
		"images/if1-sheet0.png",
		"images/isplash-sheet0.png",
		"images/ifade-sheet0.png",
		"images/ionsound-sheet0.png",
		"images/ionmusic-sheet0.png",
		"images/imusic-sheet0.png",
		"images/imusic-sheet1.png",
		"images/isom-sheet0.png",
		"images/isom-sheet1.png",
		"images/ihome-sheet0.png",
		"images/iback-sheet0.png",
		"images/ihomegame-sheet0.png",
		"images/istrengh-sheet0.png",
		"images/istrengh-sheet1.png",
		"images/ifloor-sheet0.png",
		"images/iretirarvida-sheet0.png",
		"images/ihearts-sheet0.png",
		"images/ihearts-sheet1.png",
		"images/ihearts-sheet2.png",
		"images/imonster-sheet0.png",
		"images/ifire-sheet0.png",
		"images/ilightning-sheet0.png",
		"images/iice-sheet0.png",
		"images/ibackgroundmenu-sheet0.png",
		"images/igameover-sheet0.png",
		"images/itesteparede-sheet0.png",
		"images/isensor-sheet0.png",
		"images/isensor2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/ibackgroundm-sheet0.png",
		"images/ibackgroundcs-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/ifreezet-sheet0.png",
		"images/ilightnigt-sheet0.png",
		"media/musicaprincipal.ogg",
		"media/atirando a flecha.m4a",
		"media/atirando a flecha.ogg",
		"media/gelo arco gelo.m4a",
		"media/gelo arco gelo.ogg",
		"media/raio oficial 4.m4a",
		"media/raio oficial 4.ogg",
		"media/carregando arco 2 seg.m4a",
		"media/carregando arco 2 seg.ogg",
		"media/tap 2.m4a",
		"media/tap 2.ogg",
		"media/explosão arco fogo menor.m4a",
		"media/explosão arco fogo menor.ogg",
		"media/game over 7 seg.m4a",
		"media/game over 7 seg.ogg",
		"media/monstro morrendo.m4a",
		"media/monstro morrendo.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"medieval_pixel-webfont.eot",
		"medieval_pixel-webfont.svg",
		"medieval_pixel-webfont.ttf",
		"medieval_pixel-webfont.woff",
		"medieval_pixel-webfont.woff2",
		"stylesheet.css"
	]
}